# -*- coding: utf-8 -*-
"""ATLAS  intentos fallidos e intento 5 el victorioso

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNDszYl-bmNnYmafG0oRLykU_J4Ip8NL

# Intento 1
"""

# Instalar si es necesario (SE DEMORA 7 MINUTOS en ejecutar)
install.packages(c("readr", "dplyr", "randomForest", "ggplot2", "caret"))

# Cargar librerías
library(readr)
library(dplyr)
library(randomForest)
library(ggplot2)
library(caret)

# Leer CSV
df <- read_csv("AtlasRetail_PowerBI_Final_Limpio.csv", locale = locale(decimal_mark = ","))

# Renombrar variables clave
names(df)[names(df) == "Margen_(%)"] <- "Margen_pct"
names(df)[names(df) == "Rentabilidad_(%)"] <- "Rentabilidad_pct"

df <- df %>%
  mutate(
    Margen_pct = as.numeric(gsub(",", ".", as.character(Margen_pct))),
    Rentabilidad_pct = as.numeric(gsub(",", ".", as.character(Rentabilidad_pct))),
    Costo_envio = as.numeric(gsub(",", ".", Costo_de_envio)),
    Descuento = as.numeric(gsub(",", ".", Descuento)),
    Precio_unitario = as.numeric(gsub(",", ".", Precio_Unitario_de_Venta)),
    Cantidad = as.numeric(Cantidad),
    Región = as.factor(Region),
    Categoría = as.factor(Categoria),
    Sub_Categoria = as.factor(Sub_Categoria),
    Prioridad = as.factor(Prioridad_de_orden)
  ) %>%
  select(Rentabilidad_pct, Margen_pct, Costo_envio, Descuento, Cantidad,
         Precio_unitario, Región, Categoría, Sub_Categoria, Prioridad) %>%
  na.omit()

# Filtrar outliers en Rentabilidad
Q1_r <- quantile(df$Rentabilidad_pct, 0.25)
Q3_r <- quantile(df$Rentabilidad_pct, 0.75)
IQR_r <- Q3_r - Q1_r
lim_inf_r <- Q1_r - 1.5 * IQR_r
lim_sup_r <- Q3_r + 1.5 * IQR_r

# Filtrar outliers en Margen
Q1_m <- quantile(df$Margen_pct, 0.25)
Q3_m <- quantile(df$Margen_pct, 0.75)
IQR_m <- Q3_m - Q1_m
lim_inf_m <- Q1_m - 1.5 * IQR_m
lim_sup_m <- Q3_m + 1.5 * IQR_m

# Aplicar filtros combinados
df <- df %>%
  filter(Rentabilidad_pct > lim_inf_r, Rentabilidad_pct < lim_sup_r,
         Margen_pct > lim_inf_m, Margen_pct < lim_sup_m)

nrow(df)

set.seed(42)  # Para que los resultados sean reproducibles

trainIndex <- createDataPartition(df$Rentabilidad_pct, p = 0.8, list = FALSE)
trainData <- df[trainIndex, ]
testData <- df[-trainIndex, ]

# 1ra prueba de Entrenamiento (falló se demora más de 30 minutos en procesarla y ni siquiera se ejecutó, no se esperó más)

modelo_rf <- randomForest(
  Rentabilidad_pct ~ Costo_envio + Descuento + Cantidad + Precio_unitario +
    Región + Categoría + Sub_Categoria + Prioridad,
  data = trainData,
  ntree = 500,
  mtry = 4,
  importance = TRUE
)

# 2do intento de Entrenamiento optimizado (sin Sub_Categoría y menos árboles), se demoro 17 minutos en ejecutar
modelo_rf <- randomForest(
  Rentabilidad_pct ~ Costo_envio + Descuento + Cantidad + Precio_unitario +
    Región + Categoría + Prioridad,
  data = trainData,
  ntree = 200,     # Menos árboles → más rápido
  mtry = 4,        # Número de variables probadas por división
  importance = TRUE
)

# Predicciones en test
pred <- predict(modelo_rf, newdata = testData)

# Métricas
rsq <- cor(pred, testData$Rentabilidad_pct)^2
rmse <- sqrt(mean((pred - testData$Rentabilidad_pct)^2))

cat("✅ Nuevo R²:", rsq, "\n📉 Nuevo RMSE:", rmse, "\n")

varImpPlot(modelo_rf, main = "Importancia de Variables - Modelo Optimizado")

"""# Intento 2"""

# 1. Volvemos a cargar todo con variables originales
df <- read_csv("AtlasRetail_PowerBI_Final_Limpio.csv", locale = locale(decimal_mark = ","))

names(df)[names(df) == "Margen_(%)"] <- "Margen_pct"
names(df)[names(df) == "Rentabilidad_(%)"] <- "Rentabilidad_pct"

df <- df %>%
  mutate(
    Margen_pct = as.numeric(gsub(",", ".", as.character(Margen_pct))),
    Rentabilidad_pct = as.numeric(gsub(",", ".", as.character(Rentabilidad_pct))),
    Costo_envio = as.numeric(gsub(",", ".", Costo_de_envio)),
    Descuento = as.numeric(gsub(",", ".", Descuento)),
    Precio_unitario = as.numeric(gsub(",", ".", Precio_Unitario_de_Venta)),
    Cantidad = as.numeric(Cantidad),
    Región = as.factor(Region),
    Categoría = as.factor(Categoria),
    Sub_Categoria = as.factor(Sub_Categoria),
    Prioridad = as.factor(Prioridad_de_orden)
  ) %>%
  select(Rentabilidad_pct, Margen_pct, Costo_envio, Descuento, Cantidad,
         Precio_unitario, Región, Categoría, Sub_Categoria, Prioridad) %>%
  na.omit()

# Filtrar extremos verdaderos
df <- df %>%
  filter(Rentabilidad_pct > -100, Rentabilidad_pct < 150,
         Margen_pct > -100, Margen_pct < 150)

set.seed(42)
# se demoro 22 minutos en ejecutarse
trainIndex <- createDataPartition(df$Rentabilidad_pct, p = 0.8, list = FALSE)
trainData <- df[trainIndex, ]
testData <- df[-trainIndex, ]

modelo_final <- randomForest(
  Rentabilidad_pct ~ Costo_envio + Descuento + Cantidad + Precio_unitario +
    Región + Categoría + Sub_Categoria + Prioridad,
  data = trainData,
  ntree = 200,
  mtry = 4,
  importance = TRUE
)

pred <- predict(modelo_final, newdata = testData)

rsq <- cor(pred, testData$Rentabilidad_pct)^2
rmse <- sqrt(mean((pred - testData$Rentabilidad_pct)^2))

cat("🎯 R² FINAL:", rsq, "\n💥 RMSE FINAL:", rmse, "\n")

"""# Intento 3"""

# 1. Cargar y preparar los datos
df <- read_csv("AtlasRetail_PowerBI_Final_Limpio.csv", locale = locale(decimal_mark = ","))

names(df)[names(df) == "Rentabilidad_(%)"] <- "Rentabilidad_pct"

df <- df %>%
  mutate(
    Rentabilidad_pct = as.numeric(gsub(",", ".", as.character(Rentabilidad_pct))),
    Costo_envio = as.numeric(gsub(",", ".", Costo_de_envio)),
    Descuento = as.numeric(gsub(",", ".", Descuento)),
    Precio_unitario = as.numeric(gsub(",", ".", Precio_Unitario_de_Venta)),
    Cantidad = as.numeric(Cantidad),
    Región = as.factor(Region),
    Categoría = as.factor(Categoria),
    Sub_Categoría = as.factor(Sub_Categoria),
    Prioridad = as.factor(Prioridad_de_orden)
  ) %>%
  select(Rentabilidad_pct, Costo_envio, Descuento, Cantidad, Precio_unitario,
         Región, Categoría, Sub_Categoría, Prioridad) %>%
  na.omit()

# 2. Filtrar outliers extremos reales
df <- df %>%
  filter(Rentabilidad_pct > -100, Rentabilidad_pct < 150)

# 3. Split de entrenamiento/prueba
set.seed(42)
trainIndex <- createDataPartition(df$Rentabilidad_pct, p = 0.8, list = FALSE)
trainData <- df[trainIndex, ]
testData <- df[-trainIndex, ]

# 4. Entrenar modelo Random Forest final (se demoro 21 minutos en ejecutar)
modelo_rf <- randomForest(
  Rentabilidad_pct ~ Costo_envio + Descuento + Cantidad + Precio_unitario +
    Región + Categoría + Sub_Categoría + Prioridad,
  data = trainData,
  ntree = 200,
  mtry = 4,
  importance = TRUE
)

# 5. Evaluar modelo
pred <- predict(modelo_rf, newdata = testData)
rsq <- cor(pred, testData$Rentabilidad_pct)^2
rmse <- sqrt(mean((pred - testData$Rentabilidad_pct)^2))

cat("🎯 R² FINAL:", rsq, "\n📉 RMSE FINAL:", rmse, "\n")

"""# Intento 4"""

# 1. Cargar y preparar los datos
df <- read_csv("AtlasRetail_PowerBI_Final_Limpio.csv", locale = locale(decimal_mark = ","))

names(df)[names(df) == "Rentabilidad_(%)"] <- "Rentabilidad_pct"

df <- df %>%
  mutate(
    Rentabilidad_pct = as.numeric(gsub(",", ".", as.character(Rentabilidad_pct))),
    Costo_envio = as.numeric(gsub(",", ".", Costo_de_envio)),
    Descuento = as.numeric(gsub(",", ".", Descuento)),
    Precio_unitario = as.numeric(gsub(",", ".", Precio_Unitario_de_Venta)),
    Cantidad = as.numeric(Cantidad),
    Región = as.factor(Region),
    Categoría = as.factor(Categoria),
    Sub_Categoría = as.factor(Sub_Categoria),
    Prioridad = as.factor(Prioridad_de_orden)
  ) %>%
  select(Rentabilidad_pct, Costo_envio, Descuento, Cantidad, Precio_unitario,
         Región, Categoría, Sub_Categoría, Prioridad) %>%
  na.omit()

# 2. Filtrar outliers extremos reales
df <- df %>%
  filter(Rentabilidad_pct > -100, Rentabilidad_pct < 150)

# 3. Split de entrenamiento/prueba
set.seed(42)
trainIndex <- createDataPartition(df$Rentabilidad_pct, p = 0.8, list = FALSE)
trainData <- df[trainIndex, ]
testData <- df[-trainIndex, ]

# 4. Entrenar modelo Random Forest final (se demoro 5 minutos en ejecutar) 1er intento
modelo_rf <- randomForest(
  Rentabilidad_pct ~ Costo_envio + Descuento + Cantidad + Precio_unitario +
    Región + Categoría + Prioridad + Sub_Categoría,
  data = trainData,
  ntree = 300,
  mtry = 2,
  importance = TRUE
)

# 4. Entrenar modelo Random Forest final (se demoro 5 minutos en ejecutar) 2do intento
modelo_rf <- randomForest(
  Rentabilidad_pct ~ Costo_envio + Descuento + Cantidad + Precio_unitario +
    Región + Categoría + Prioridad + Sub_Categoría,
  data = trainData,
  ntree = 200,
  mtry = 4,
  importance = TRUE
)

# 5. Evaluar modelo
pred <- predict(modelo_rf, newdata = testData)
rsq <- cor(pred, testData$Rentabilidad_pct)^2
rmse <- sqrt(mean((pred - testData$Rentabilidad_pct)^2))

cat("🎯 R² FINAL:", rsq, "\n📉 RMSE FINAL:", rmse, "\n")

"""# Recomendación chat y explicación

🎓 ¿Es posible llegar a R² = 0.90 con tu dataset?
Respuesta corta: Muy difícil, casi imposible sin datos adicionales o sin cambiar de modelo completamente.

🧠 ¿Por qué?
Tu variable Rentabilidad_pct está influida por muchas cosas que no están en el dataset, por ejemplo: Políticas internas de descuentos, Costos variables no registrados (como comisiones o devoluciones), Comportamiento del cliente (urgencia, satisfacción), Promociones cruzadas, logística interna, temporada, etc.

👉 Como todo eso no está modelado, el modelo no puede explicar el 90% de la variabilidad. Estás tratando de predecir un fenómeno multicausal con información incompleta.

🔬 ¿Qué alternativas reales tienes para mejorar?
✅ 1. Probar otro modelo más potente: XGBoost
Mucho más preciso que Random Forest si se entrena bien.

PERO: es más difícil de calibrar y más sensible a errores.

✅ 2. Crear nuevas variables derivadas (feature engineering)
Por ejemplo:

Margen_vs_Precio_unitario

Descuento_por_categoria

Ratio_descuento/costo_total

Eso aumenta la capacidad explicativa del modelo.

✅ 3. Usar regresión múltiple con lm() como comparación
Aunque no mejora el poder predictivo, te puede servir para ver si Random Forest realmente lo está haciendo mal o ya estás en el tope técnico de lo que permiten los datos.

📉 La realidad es:
Modelo	R² típico en negocios	RMSE razonable
Random Forest (real)	0.60–0.75	15–20
Modelos ideales con más variables ocultas	0.85–0.95	5–10

🛑 Entonces:
No es que tú lo estés haciendo mal.

👉 Es que los datos que tienes no contienen la explicación suficiente para llegar a 90% de R².

# Intento 5
"""

df <- read_csv("AtlasRetail_PowerBI_Final_Limpio.csv", locale = locale(decimal_mark = ","))

names(df)[names(df) == "Rentabilidad_(%)"] <- "Rentabilidad_pct"
names(df)[names(df) == "Margen_(%)"] <- "Margen_pct"

df <- df %>%
  mutate(
    Rentabilidad_pct = as.numeric(gsub(",", ".", Rentabilidad_pct)),
    Margen_pct = as.numeric(gsub(",", ".", Margen_pct)),
    Costo_envio = as.numeric(gsub(",", ".", Costo_de_envio)),
    Descuento = as.numeric(gsub(",", ".", Descuento)),
    Precio_unitario = as.numeric(gsub(",", ".", Precio_Unitario_de_Venta)),
    Costo_total = as.numeric(gsub(",", ".", Costo_Total)),
    Cantidad = as.numeric(Cantidad),
    Región = as.factor(Region),
    Categoría = as.factor(Categoria),
    Sub_Categoría = as.factor(Sub_Categoria),
    Prioridad = as.factor(Prioridad_de_orden)
  ) %>%
  select(Rentabilidad_pct, Margen_pct, Costo_envio, Descuento, Precio_unitario,
         Costo_total, Cantidad, Región, Categoría, Sub_Categoría, Prioridad) %>%
  na.omit()

# 2. Crear variables derivadas
df <- df %>%
  mutate(
    Margen_vs_Precio_unitario = ifelse(Precio_unitario == 0, 0, Margen_pct / Precio_unitario),
    Ratio_descuento_costo = ifelse(Costo_envio == 0, 0, Descuento / Costo_envio)
  )

# 3. Descuento promedio por categoría
prom_descuento <- df %>%
  group_by(Categoría) %>%
  summarise(Desc_por_categoria = mean(Descuento, na.rm = TRUE))

df <- left_join(df, prom_descuento, by = "Categoría")

# 4. Filtrar outliers extremos de Rentabilidad
df <- df %>%
  filter(Rentabilidad_pct > -100, Rentabilidad_pct < 150)

# 5. División entrenamiento / prueba
set.seed(42)
trainIndex <- createDataPartition(df$Rentabilidad_pct, p = 0.8, list = FALSE)
trainData <- df[trainIndex, ]
testData <- df[-trainIndex, ]

# 6. Entrenar modelo con nuevas variables (se demoro 17 min en ejecutarse)
modelo_rf <- randomForest(
  Rentabilidad_pct ~ Costo_envio + Descuento + Precio_unitario + Costo_total + Cantidad +
    Región + Categoría + Sub_Categoría + Prioridad +
    Margen_vs_Precio_unitario + Ratio_descuento_costo + Desc_por_categoria,
  data = trainData,
  ntree = 200, #<------------ bajitooo
  mtry = 4,
  importance = TRUE
)

# 6. Entrenar modelo con nuevas variables (se demoro 26 minutos)
modelo_rf <- randomForest(
  Rentabilidad_pct ~ Costo_envio + Descuento + Precio_unitario + Costo_total + Cantidad +
    Región + Categoría + Sub_Categoría + Prioridad +
    Margen_vs_Precio_unitario + Ratio_descuento_costo + Desc_por_categoria,
  data = trainData,
  ntree = 300,
  mtry = 4,
  importance = TRUE
)

# 7. Evaluación del modelo
pred <- predict(modelo_rf, newdata = testData)
rsq <- cor(pred, testData$Rentabilidad_pct)^2
rmse <- sqrt(mean((pred - testData$Rentabilidad_pct)^2))

cat("🎯 R² FINAL:", rsq, "\n📉 RMSE FINAL:", rmse, "\n")

levels(df$Región)
levels(df$Categoría)
levels(df$Sub_Categoría)
levels(df$Prioridad)

# Categorías y sus Sub_Categorías válidas:

# Furniture:
#   - Chairs, Tables, Bookcases, Furnishings

# Office Supplies:
#   - Binders, Paper, Labels, Storage, Supplies, Art

# Technology:
#   - Phones, Accessories, Machines, Copiers

df %>%
  group_by(Categoría) %>%
  summarise(Desc_por_categoria = mean(Descuento, na.rm = TRUE))

mean(df$Margen_pct / df$Precio_unitario, na.rm = TRUE)

# Ejemplo: nuevo dato (puedes cambiar los valores)
nuevo_dato <- data.frame(
  Costo_envio = 3000,
  Descuento = 0.4,
  Precio_unitario = 100,
  Costo_total = 60000,
  Cantidad = 2,
  Región = factor("Southeast Asia", levels = levels(df$Región)),
  Categoría = factor("Furniture", levels = levels(df$Categoría)),
  Sub_Categoría = factor("Chairs", levels = levels(df$Sub_Categoría)),
  Prioridad = factor("Critical", levels = levels(df$Prioridad)),
  Margen_vs_Precio_unitario = 0.20,       # Calculado o estimado
  Ratio_descuento_costo = 0.10,         # Descuento / Costo_envio
  Desc_por_categoria = 0.10               # Promedio según categoría
)

# Predicción
pred_rentabilidad <- predict(modelo_rf, newdata = nuevo_dato)

# Mostrar resultado
cat("🔮 Predicción de Rentabilidad (%) =", round(pred_rentabilidad, 2), "%\n")